version: '3.7'

services:
  angular:
    build:
      context: .
      dockerfile: ui/Dockerfile
    volumes:
      - ./ui/src:/usr/src/app/src
    ports:
      - 4200:4200
  
  express:
    build: ./server
    command: nodemon server.js
    volumes:
      - ./server/src:/usr/src/app/src
    ports:
      - "3000:3000"
    links:
      - database

  mongo-seed:
    build: ./mongo-seed
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
  